security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        # Firewall qui intercepte la route de login API
        login:
            pattern: ^/api/v1/login
            stateless: true
            json_login:
                check_path: /api/v1/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Firewall qui gère les routes de l'API
        api:
            pattern:   ^/api/v1
            stateless: true
            jwt: ~

        # Routes de dev
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Toutes les autres du projet (l'appli HTML O'flix front/back)
        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: login
                check_path: login

            logout:
                
                path: logout

    access_control:

        - { path: ^/movie/.+/review/add, roles: ROLE_USER }

        - { path: ^/back/(movie|season|user)/new, roles: ROLE_ADMIN }
        - { path: ^/back/(movie|season|user)/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/back/(movie|season|user)/\d+, roles: ROLE_ADMIN, methods: POST }

        - { path: ^/back, roles: ROLE_MANAGER }

        - { path: ^/api/v1/movies, methods: POST, roles: ROLE_ADMIN }
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_MANAGER
        ROLE_MANAGER: ROLE_USER

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
