# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # Si on souhaite remonter la config dans le .env
    favorites_empty_enabled: '%env(bool:FAVORITES_EMPTY_ENABLED)%'
    omdbapi_key: '%env(OMDBAPI_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Configuration de nos services
    App\Service\FavoritesManager:
        arguments:
            $emptyEnabled: '%favorites_empty_enabled%'

    App\Service\MySlugger:
        arguments:
            $toLower: true

    App\Service\OmdbApi:
        arguments:
            $apiKey: '%omdbapi_key%'
    
    App\EventSubscriber\MaintenanceSubscriber:
        arguments:
            $isMaintenance: false
            
    App\EventListener\MovieSluggerListener:
        tags:
            -
                # these are the options required to define the entity listener
                name: 'doctrine.orm.entity_listener'
                # Type d'événement, ici, avant INSERT INTO
                event: 'prePersist'
                # L'entité à écouter
                entity: 'App\Entity\Movie'
                # La méthode du listener à appeler
                method: 'setSlug'
            -
                # these are the options required to define the entity listener
                name: 'doctrine.orm.entity_listener'
                # Type d'événement, ici, avant UPDATE
                event: 'preUpdate'
                # L'entité à écouter
                entity: 'App\Entity\Movie'
                # La méthode du listener à appeler
                method: 'setSlug'

    